sudo: false

matrix:
  include:
    - os: linux
      compiler: gcc
      addons: &gcc46
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.6', 'gcc-4.6']
      env:
        - CXX='g++-4.6'
        - CC='gcc-4.6'
    - os: osx
      compiler: gcc
      env:
        - CXX='g++-4.6'
        - CC='gcc-4.6'

before_install:
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then brew install gcc46; fi

script:
  - ${CC} --version
  - env
  - ${CC} -print-file-name=plugin
  - ${CC} -print-file-name=plugin/include/gcc-plugin.h
  - ${CC} -print-file-name=gcc-plugin.h
  - make

notifications:
    email: true
